### ISSUE TITLE
macOS support?

### ISSUE THREAD

**Issue by iSapozhnik** [bannzai/Gedatsu#18]
Thanks for a great tool. Is there any chance to see that for macOS?

**Comment by bannzai** [comment]
Good idea!! I will try it tommorow.

**Comment by iSapozhnik** [comment]
> Good idea!! I will try it tommorow.

Ideally by extending `Package.swift` to support macOS and few more lines to handle both `UIView` and `NSView` everything should work out of the box :)

**Comment by bannzai** [comment]
@iSapozhnik Thank you for your advice 😄 

Fix https://github.com/bannzai/Gedatsu/pull/24

**Comment by iSapozhnik** [comment]
Thanks you! 👍
