### ISSUE TITLE
Gedatsu crashes if the view whose translatesAutoresizingMaskIntoConstraints property is true is in the ambiguous view tree. 

### ISSUE THREAD

**Issue by mogaming217** [bannzai/Gedatsu#26]
Below code, maybe you can reproduce the crash. I tried to test in iOS 12.2 and 13.5.
In the lldb, `po self.rawValue` is 35.

<img width="956" alt="スクリーンショット 2020-06-05 15 57 22" src="https://user-images.githubusercontent.com/10220231/83849220-0914d480-a74a-11ea-8ce2-9e26cf6e2a75.png">

It does not crash if `translatesAutoresizingMaskIntoConstraints` property of `footerButton` and `footerView` is false.

```
class ViewController: UITableViewController {
    let footerButton: UIButton = {
        let button = UIButton()
        button.setTitle("Button Label", for: .normal)
        return button
    }()
    lazy var footerView: UIView = {
        let view = UIView()
        view.addSubview(self.footerButton)
        NSLayoutConstraint.activate([
            footerButton.centerXAnchor.constraint(equalTo: view.centerXAnchor),
            footerButton.centerYAnchor.constraint(equalTo: view.centerYAnchor),
            footerButton.topAnchor.constraint(equalTo: view.topAnchor, constant: 32)
        ])
        return view
    }()

    override func viewDidLoad() {
        super.viewDidLoad()
        tableView.tableFooterView = footerView
    }
}
```

**Comment by bannzai** [comment]
@mogaming217 AutoLayoutの作法的に `translatesAutoresizingMaskIntoConstraints = false` をするとAutoLatoutが有効になります。今回のはAutoLayoutが無効になっている場合において `NSLayoutConstraint.Attributes` に `case` ではカバーしきれていない値が入ってくるから起きたクラッシュみたいですね。エラーメッセージを工夫するかなりして改善します。ありがとう！

**Comment by mogaming217** [comment]
>  AutoLayoutの作法的に translatesAutoresizingMaskIntoConstraints = false をするとAutoLatoutが有効になります。

はい！僕が完全に書くのを忘れていてたまたま引き当てちゃった感じだったので、基本的には起こらないものだと思うので、なんか良き時に対応いただければと〜〜！
